// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var twitterButton;
    console.log('index started');
    $(".title").fitText(1.0, {
      minFontSize: 30,
      maxFontSize: 50
    });
    twitterButton = function(d, s, id) {
      var fjs, js;
      fjs = d.getElementsByTagName(s)[0];
      if (!d.getElementById(id)) {
        js = d.createElement(s);
        js.id = id;
        js.src = "http://platform.twitter.com/widgets.js";
        return fjs.parentNode.insertBefore(js, fjs);
      }
    };
    return twitterButton(document, "script", "twitter-wjs");
  });

}).call(this);
